variables:
  OPAM_SYS_DEPLOY_FOLDER_WINDOWS: 'C:\DiskuvOCaml\OpamSys'

default:
  image: python:3.9-alpine

  before_script:
    - apk add --no-cache make rsync
    - pip install -U sphinx sphinx_rtd_theme

stages:
  - prepare
  - build
  - test
  - deploy

include:
  - local: .gitlab/ci/pages.gitlab-ci.yml
  - local: .gitlab/ci/test.gitlab-ci.yml
  - local: .gitlab/ci/unix-package-ocaml.gitlab-ci.yml
  - local: .gitlab/ci/windows.gitlab-ci.yml
  - local: .gitlab/ci/windows-package-ocaml.gitlab-ci.yml
  - local: .gitlab/ci/windows-package-opam.gitlab-ci.yml
  - local: .gitlab/ci/windows-package-ocaml-opam-repo.gitlab-ci.yml
  - local: .gitlab/ci/windows-test-setupuserprofile.gitlab-ci.yml
