pages:
  stage: deploy
  script:
  - echo Building Sphinx html twice so that Sphinx cross-references work ...
  - make -C contributors html ; make -C contributors html O="-W"
  - echo Copying HTML into the GitLab Pages required 'public' folder
  - rsync -av contributors/_build/html/ public
  artifacts:
    paths:
    - public
    expire_in: 1 day
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
