windows:test-setupuserprofile:
  variables:
    SKIP_VISUAL_STUDIO_INSTALL: 'ON'
  extends:
  - .windows:before-script-shared-msys2-setupmachine
  stage: build
  needs: []
  rules:
    # - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_BRANCH == "next"'
  script:
    - $env:MSYSTEM = 'MSYS2'       # Start MSYS2 (not MinGW 32 or 64 bit) environments
    - date
