windows:build-opam:
  extends:
    - .windows:before-script-shared-msys2-setupmachine
  stage: build
  parallel:
    matrix:
      - BITS: 32
        PLATFORM: windows_x86
      - BITS: 64
        PLATFORM: windows_x86_64
  needs: []
  rules:
    # - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_BRANCH == "next"'
  script:
    - $env:MSYSTEM = 'MSYS2' # Start MSYS2 (not MinGW 32 or 64 bit) environments
    - $DEPLOYDIR = "$env:OPAM_SYS_DEPLOY_FOLDER_WINDOWS\$env:BITS" # Separate directories only so that job can be run in parallel
    - if (!(Test-Path "$DEPLOYDIR")) { New-Item -Path "$DEPLOYDIR" -ItemType Directory }

    # ================ Prepare ================
    # Theoretically these should go in a separate job. However the GitLab runner takes 5-10 minutes to spin up a Windows container
    # so this is all in one job

    # ----------- Chocolatey -----------

    # Git (not part of GitLab Windows Shared Runner images)
    # (Choco best practices: https://docs.chocolatey.org/en-us/choco/commands/#scripting-integration-best-practices-style-guide)
    - choco upgrade git.install -y --no-progress --version="'2.33.0.2'" --package-parameters "'/GitOnlyOnPath /NoGitLfs /SChannel /NoAutoCrlf'"
    - refreshenv
    - where.exe git.exe

    # ================ Build ================

    - msys (
      'env'
      + ' TOPDIR=$PWD/installtime/none/emptytop'
      + ' installtime/unix/private/reproducible-compile-opam-1-setup.sh'
      + " -d '" + "$PWD" + "'"
      + " -a " + "$env:PLATFORM"
      + " -b " + "$($VisualStudioProps.MsvsPreference)"
      + " -t '" + "$DEPLOYDIR" + "'"
      + " -u https://github.com/diskuv/opam"
      + " -v " + $DV_AvailableOpamVersion
      )
    - msys ("cd '" + "$DEPLOYDIR" + ''' && share/dkml/repro/110-compile-opam/installtime/unix/private/reproducible-compile-opam-2-build-noargs.sh')
    - msys ("cd '" + "$DEPLOYDIR" + ''' && share/dkml/repro/110-compile-opam/installtime/unix/private/reproducible-compile-opam-9-trim-noargs.sh')
    - if (!(Test-Path -Path "$DEPLOYDIR\bin\opam.exe")) { throw "Build failed" }

    # Create .tar.gz and .zip
    - New-Item -Path "$EXTRASRC\opamdist" -ItemType Directory
    - msys ('/usr/bin/tar cvCfz ''' + "$DEPLOYDIR" + ''' _ci/opamdist/dist.tar.gz .')
    - Compress-Archive -Path "$DEPLOYDIR\*" -DestinationPath "$EXTRASRC\opamdist\dist.zip"

    # Create public packages
    - if ("${env:CI_COMMIT_TAG}" -ne "") { $PACKAGE_REGISTRY_URL = "$PACKAGE_REGISTRY_GENERIC_URL/opam-reproducible/${env:CI_COMMIT_TAG}"; }
    - if ("${env:CI_COMMIT_TAG}" -ne "") { echo $PACKAGE_REGISTRY_URL; }
    - if ("${env:CI_COMMIT_TAG}" -ne "") { msys "curl --fail --header '$GLAB_CURL_HEADER' --upload-file _ci/opamdist/dist.tar.gz '$PACKAGE_REGISTRY_URL'/opam-win${env:BITS}.tar.gz"; }
    - if ("${env:CI_COMMIT_TAG}" -ne "") { msys "curl --fail --header '$GLAB_CURL_HEADER' --upload-file _ci/opamdist/dist.zip    '$PACKAGE_REGISTRY_URL'/opam-win${env:BITS}.zip"; }
