# Split tests into multiple jobs so that can stay within 1hour timelimit on GitLab CI shared runners.
# Each test job will populate the cache so the next job can go quickly.

.test_before: &test-before
    - date
    - $env:MSYSTEM = 'MSYS2'       # Start MSYS2 (not MinGW 32 or 64 bit) environments
    - $global:IncrementalDiskuvOcamlDeployment = $true # Use incremental deployments so cache can be re-used.
    - |
      function msys_direct() {
        $path_unix = & "$env:CI_PROJECT_DIR\_ci\LocalAppData\Programs\DiskuvOCaml\0\tools\MSYS2\usr\bin\cygpath" --path "$env:PATH" ;
        & "$env:CI_PROJECT_DIR\_ci\LocalAppData\Programs\DiskuvOCaml\0\tools\MSYS2\usr\bin\bash.exe" @('-lc') + ("set -eufx -o pipefail; cd '$env:CI_PROJECT_DIR'; PATH=`"`$PATH`":'${path_unix}'; " + $Args[0]);
      }
    # Pretend to setup-userprofile.bat that LOCALAPPDATA is part of the project so we can cache DiskuvOCaml installations without modification
    - $OldLocalAppData = "$env:LOCALAPPDATA"
    - $env:LOCALAPPDATA = "$env:CI_PROJECT_DIR\_ci\LocalAppData"
    - if (!(Test-Path "$env:LOCALAPPDATA")) { New-Item -Path "$env:LOCALAPPDATA" -ItemType Directory }

windows:test-setupuserprofile-1-before-create-system-switch:
  variables:
    SKIP_VISUAL_STUDIO_INSTALL: 'ON'
  extends:
  - .windows:before-script-shared-setupmachine
  stage: build
  needs: []
  rules:
    # - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_BRANCH == "next"'
  cache:
    key:
      files:
        - contributors\.userprofile.cachekey
    paths:
      - _ci\LocalAppData\Programs\DiskuvOCaml
      - _ci\LocalAppData\opam
      - _ci\LocalAppData\vcpkg

  script:
    - *test-before

    # Test Deployers module
    - $env:PSModulePath += "$([System.IO.Path]::PathSeparator)$env:CI_PROJECT_DIR\installtime\windows"
    - Import-Module Deployers
    - Invoke-BlueGreenDeployTests

    # Call setup-userprofile.bat
    # Use incremental deployments and slot 0 so cache can be re-used.
    - installtime\windows\setup-userprofile.ps1 -SkipProgress -AllowRunAsAdmin -ForceDeploymentSlot0 -StopBeforeCreateSystemSwitch
    - msys_direct 'tree -L 5 _ci/LocalAppData'

    # Clean up cache
    - $DkmlProps = ConvertFrom-StringData (Get-Content "$env:CI_PROJECT_DIR\.dkmlroot" -Raw)
    - $dkml_root_version = $DkmlProps.dkml_root_version
    - Get-ChildItem -Path "$env:CI_PROJECT_DIR\_ci\LocalAppData\opam\plugins" -Recurse | Select -ExpandProperty FullName | Where {$_ -notlike "$dkml_root_version"} | Sort-Object length -Descending | Remove-Item -Force
    - Get-ChildItem -Path "$env:CI_PROJECT_DIR\_ci\LocalAppData\Programs\DiskuvOCaml\opam-repositories" -Recurse -Exclude "$dkml_root_version.complete" | Select -ExpandProperty FullName | Where {$_ -notlike "$dkml_root_version"} | Sort-Object length -Descending | Remove-Item -Force
    - Get-ChildItem -Path "$env:CI_PROJECT_DIR\_ci\LocalAppData\opam\repo" -Recurse -Exclude default.tar.gz,repos-config,state-*.cache,"diskuv-$dkml_root_version.tar.gz","fdopen-mingw-$dkml_root_version.tar.gz" | Select -ExpandProperty FullName | Sort-Object length -Descending | Remove-Item -Force
    - msys_direct 'tree -L 5 _ci/LocalAppData'

    # Remove Cygwin if present since not needed for cache (it is only an intermediate tool for downloading ocaml-opam Docker repository)
    - msys_direct 'rm -rf _ci/LocalAppData/Programs/DiskuvOCaml/0/tools/cygwin'

    - date

windows:test-setupuserprofile-2-install-system-switch:
  variables:
    SKIP_VISUAL_STUDIO_INSTALL: 'ON'
  extends:
  - .windows:before-script-shared-setupmachine
  stage: build
  needs: ["windows:test-setupuserprofile-1-before-create-system-switch"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "next"'
  cache:
    key:
      files:
        - contributors\.userprofile.cachekey
    paths:
      - _ci\LocalAppData\Programs\DiskuvOCaml
      - _ci\LocalAppData\opam
      - _ci\LocalAppData\vcpkg
  script:
    - *test-before
    - installtime\windows\setup-userprofile.ps1 -SkipProgress -AllowRunAsAdmin -ForceDeploymentSlot0 -StopBeforeInstallSystemSwitch
    - msys_direct 'tree -L 5 _ci/LocalAppData'
    - date

windows:test-setupuserprofile-3-remaining:
  variables:
    SKIP_VISUAL_STUDIO_INSTALL: 'ON'
  extends:
  - .windows:before-script-shared-setupmachine
  stage: build
  needs: ["windows:test-setupuserprofile-2-install-system-switch"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "next"'
  cache:
    key:
      files:
        - contributors\.userprofile.cachekey
    paths:
      - _ci\LocalAppData\Programs\DiskuvOCaml
      - _ci\LocalAppData\opam
      - _ci\LocalAppData\vcpkg
  script:
    - *test-before
    - installtime\windows\setup-userprofile.ps1 -SkipProgress -AllowRunAsAdmin -ForceDeploymentSlot0
    - msys_direct 'tree -L 5 _ci/LocalAppData' ; $true
